# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BurnIt_1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  source 'https://github.com/CocoaPods/Specs.git'
    pod ‘Alamofire’
    pod ‘ObjectMapper’
    pod ‘AlamofireObjectMapper’
    pod ‘Kingfisher’
    pod ‘SwiftyJSON’
    pod ‘GoogleMaps’
    pod ‘GooglePlaces’
    pod ‘GooglePlacesSearchController’
    pod ‘Cosmos’
    pod ‘lottie-ios’

end
